language: scala
jdk:
- openjdk8
scala:
- 2.12.10
- 2.13.1
script:
- sbt --info ++$TRAVIS_SCALA_VERSION publishLocal
- sbt --warn ++$TRAVIS_SCALA_VERSION -DplayTestVersion=2.8.0-RC1 test
after_success:
- ! '[[ $TRAVIS_BRANCH == "master" ]] && { sbt +publish; };'
- python <(curl -s https://raw.githubusercontent.com/TouK/sputnik-ci/master/sputnik-ci.py)
sudo: false
